import withMT from '@material-tailwind/react/utils/withMT';

export default withMT({
  content: [
    './index.html',
    './src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'bitter-chocolate': '#4F443F',
        'french-chateau': '#E6E3D6',
        'ocean-pearl': '#D3CFBD',
        'off-broadway': '#433F3D',
        'antique-tin': '#6E7173',
        'greyhouse':'#808080',
        'dark': '#232A3C',
        'medium': '#293245',
        'saddle-brown': '#74431D',
        'sienna': '#A17544',
        'sienna2': '#AC6C3F',
        'dark-olive-green': '#2C1B14',
        'light-grey': '#D1D1CC',
        'slate-grey': '#7F8C83',
        'woods-black': '#383633',
        'woods-taupe': '#947048',
        'woods-tan': '#d6cbb9',
        'woods-rust': '#735237',
        'woods-gray': '#a38a6f',
        'woods-red': '#8f6242',
        'woods-black-dark': '#c7c9cc',
        'woods-taupe-dark': '#6b8fb7',
        'woods-tan-dark': '#293446',
        'woods-rust-dark': '#8cadc8',
        'woods-gray-dark': '#5c7590',
        'woods-red-dark': '#709dbd',
        // 'woods-black': '#2f1a13',
        // 'woods-taupe': '#b46c4c',
        // 'woods-tan': '#d1c8bb',
        // 'woods-rust': '#5a4339',
        // 'woods-black': '#735335',
        // 'woods-taupe': '#8f7438',
        // 'woods-tan': '#eae4d1',
        // 'woods-rust': '#b48156',
        // 'woods-black': '#411308',
        // 'woods-taupe': '#b37835',
        // 'woods-tan': '#edd6b6',
        // 'woods-rust': '#171313',
        // 'woods-black': '#1c1911',
        // 'woods-black': '#212221',
        // 'woods-taupe': '#1181B2',
        // 'woods-taupe': '#3F6844',
        // 'woods-taupe': '#695b52',
        // 'woods-tan': '#DDEDF4',
        // 'woods-tan': '#FAF1CF',
        // 'woods-tan': '#b09e93',
        // 'woods-rust': '#44449B',
        // 'woods-rust': '#5DAA68',
        // 'woods-rust': '#ae7324',
        // 'gentle-earth1' : '#',
        // 'gentle-earth2' : '#',
        // 'gentle-earth3' : '#',
        // 'gentle-earth4' : '#',
        // 'vintage-earth1' : '#',
        // 'vintage-earth2' : '#',
        // 'vintage-earth3' : '#',
        // 'vintage-earth4' : '#',
        'natural-serenity1' : '#7a6136',
        'natural-serenity2' : '#dbd0c5',
        'natural-serenity3' : '#a8896e',
        'natural-serenity4' : '#464225',
      },
      animation: {
        'spin-slow': 'spin 5s linear infinite',
      }
    },
  },
  plugins: [],
})
  


